In [5]:
import pandas as pd

In [6]:
df=pd.read_csv("../data/athlete_events.csv")
regions=pd.read_csv("../data/noc_regions.csv")

In [8]:
df.head()

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold
4,5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,Netherlands,NED,1988 Winter,1988,Winter,Calgary,Speed Skating,Speed Skating Women's 500 metres,NaN

In [9]:
df=df.merge(regions, on='NOC', how='left')

In [10]:
df.head()

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal,region,notes
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN,China,NaN
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN,China,NaN
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN,Denmark,NaN
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold,Denmark,NaN
4,5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,Netherlands,NED,1988 Winter,1988,Winter,Calgary,Speed Skating,Speed Skating Women's 500 metres,NaN,Netherlands,NaN

In [11]:
df=df.drop(columns=['notes'])

In [12]:
df.head()

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal,region
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN,China
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN,China
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN,Denmark
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold,Denmark
4,5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,Netherlands,NED,1988 Winter,1988,Winter,Calgary,Speed Skating,Speed Skating Women's 500 metres,NaN,Netherlands

In [13]:
df.shape

(271116, 16)

In [19]:
df.sample(5)

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal,region
156323,78506,Vyacheslav Borisovich Melnikov,M,NaN,NaN,NaN,Soviet Union,URS,1956 Winter,1956,Winter,Cortina d'Ampezzo,Alpine Skiing,Alpine Skiing Men's Slalom,NaN,Russia
30776,15855,Martin Brustmann,M,20.0,NaN,NaN,Germany,GER,1906 Summer,1906,Summer,Athina,Athletics,Athletics Men's Standing Long Jump,NaN,Germany
34885,17981,Attilio Cantoni,M,25.0,182.0,80.0,Italy,ITA,1956 Summer,1956,Summer,Melbourne,Rowing,Rowing Men's Coxless Fours,NaN,Italy
206246,103528,Galen Rupp,M,22.0,181.0,61.0,United States,USA,2008 Summer,2008,Summer,Beijing,Athletics,"Athletics Men's 10,000 metres",NaN,USA
234186,117446,Gza Szegedy,M,NaN,NaN,NaN,Hungary,HUN,1906 Summer,1906,Summer,Athina,Athletics,Athletics Men's Standing High Jump,NaN,Hungary

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 271116 entries, 0 to 271115
Data columns (total 16 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   ID      271116 non-null  int64
 1   Name    271116 non-null  object
 2   Sex     271116 non-null  object
 3   Age     261642 non-null  float64
 4   Height  210945 non-null  float64
 5   Weight  208241 non-null  float64
 6   Team    271116 non-null  object
 7   NOC     271116 non-null  object
 8   Games   271116 non-null  object
 9   Year    271116 non-null  int64
 10  Season  271116 non-null  object
 11  City    271116 non-null  object
 12  Sport   271116 non-null  object
 13  Event   271116 non-null  object
 14  Medal   39783 non-null   object
 15  region  270746 non-null  object
dtypes: float64(3), int64(2), object(11)
memory usage: 33.1+ MB

In [20]:
df=df.drop(columns=['Games'])

In [21]:
df.sample(5)

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Year,Season,City,Sport,Event,Medal,region
190973,95914,Orlando Polmonari,M,36.0,NaN,NaN,Italy,ITA,1960,Summer,Roma,Gymnastics,Gymnastics Men's Horizontal Bar,NaN,Italy
33301,17162,Luis Francis Mendiola Cabral,M,32.0,NaN,NaN,Guam,GUM,1992,Summer,Barcelona,Archery,Archery Men's Individual,NaN,Guam
141472,70983,Olaf Lodal,M,26.0,NaN,NaN,Denmark,DEN,1912,Summer,Stockholm,Athletics,Athletics Men's Marathon,NaN,Denmark
265885,133032,Alexandre Felske Tadayuke Yokochi,M,27.0,180.0,76.0,Portugal,POR,1992,Summer,Barcelona,Swimming,Swimming Men's 200 metres Breaststroke,NaN,Portugal
216599,108748,Raimo Kalevi Seppnen,M,29.0,167.0,66.0,Finland,FIN,1980,Winter,Lake Placid,Biathlon,Biathlon Men's 4 x 7.5 kilometres Relay,NaN,Finland

In [22]:
df.isnull().sum()

ID             0
Name           0
Sex            0
Age         9474
Height     60171
Weight     62875
Team           0
NOC            0
Year           0
Season         0
City           0
Sport          0
Event          0
Medal     231333
region       370
dtype: int64

In [23]:
df.shape

(271116, 15)

In [24]:
df['Medal']

0          NaN
1          NaN
2          NaN
3         Gold
4          NaN
          ...
271111     NaN
271112     NaN
271113     NaN
271114     NaN
271115     NaN
Name: Medal, Length: 271116, dtype: object

In [25]:
df.describe()

,ID,Age,Height,Weight,Year
count,271116.000000,261642.000000,210945.000000,208241.000000,271116.000000
mean,68248.954396,25.556898,175.338970,70.702393,1978.378480
std,39022.286345,6.393561,10.518462,14.348020,29.877632
min,1.000000,10.000000,127.000000,25.000000,1896.000000
25%,34643.000000,21.000000,168.000000,60.000000,1960.000000
50%,68205.000000,24.000000,175.000000,70.000000,1988.000000
75%,102097.250000,28.000000,183.000000,79.000000,2002.000000
max,135571.000000,97.000000,226.000000,214.000000,2016.000000

In [26]:
df.duplicated().sum()

np.int64(1385)

In [27]:

df.loc[df['NOC'] == 'SGP', 'region'] = 'Singapore'
df.loc[df['NOC'] == 'ROT', 'region'] = 'Refugee Olympic Team'
df.loc[df['NOC'] == 'UNK', 'region'] = 'Unknown'
df.loc[df['NOC'] == 'TUV', 'region'] = 'Tuvalu'

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 271116 entries, 0 to 271115
Data columns (total 15 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   ID      271116 non-null  int64
 1   Name    271116 non-null  object
 2   Sex     271116 non-null  object
 3   Age     261642 non-null  float64
 4   Height  210945 non-null  float64
 5   Weight  208241 non-null  float64
 6   Team    271116 non-null  object
 7   NOC     271116 non-null  object
 8   Year    271116 non-null  int64
 9   Season  271116 non-null  object
 10  City    271116 non-null  object
 11  Sport   271116 non-null  object
 12  Event   271116 non-null  object
 13  Medal   39783 non-null   object
 14  region  271116 non-null  object
dtypes: float64(3), int64(2), object(10)
memory usage: 31.0+ MB

In [29]:
df.isnull().sum()

ID             0
Name           0
Sex            0
Age         9474
Height     60171
Weight     62875
Team           0
NOC            0
Year           0
Season         0
City           0
Sport          0
Event          0
Medal     231333
region         0
dtype: int64